[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18.20.0"

[functions]
  external_node_modules = ["express", "@prisma/client", "prisma", "resend"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback for client-side rouwting
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
